In [8]:
import numpy as np
import os
import json
import pandas as pd

# input string json
input_ = open(file="2015/day_15.txt", mode='r').read()

#parse
ing = json.loads(input_)
df_ing = pd.DataFrame(ing)

In [26]:
ing

{'Sprinkles': {'capacity': 5,
  'durability': -1,
  'flavor': 0,
  'texture': 0,
  'calories': 5},
 'PeanutButter': {'capacity': -1,
  'durability': 3,
  'flavor': 0,
  'texture': 0,
  'calories': 1},
 'Frosting': {'capacity': 0,
  'durability': -1,
  'flavor': 4,
  'texture': 0,
  'calories': 6},
 'Sugar': {'capacity': -1,
  'durability': 0,
  'flavor': 0,
  'texture': 2,
  'calories': 8}}

In [14]:
df_ing

Sprinkles  PeanutButter  Frosting  Sugar
capacity            5            -1         0     -1
durability         -1             3        -1      0
flavor              0             0         4      0
texture             0             0         0      2
calories            5             1         6      8

In [34]:
df_ing.index[:-1]

Index(['capacity', 'durability', 'flavor', 'texture'], dtype='object')

In [36]:
matrix_coef = df_ing.loc[df_ing.index[:-1]].to_numpy()
matrix_coef

array([[ 5, -1,  0, -1],
       [-1,  3, -1,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  2]])

In [37]:
valuels = np.dot(matrix_coef, np.array([10,10,10,70]))
valuels

array([-30,  10,  40, 140])

In [38]:
75*25*100*50*500

4687500000

In [39]:
np.prod(valuels)

-1680000

In [40]:
(valuels <= 0).sum()

1

In [43]:
score = 0
for i in range(0,101):
    for j in range(0,101-i):
        for k in range(0,101-i-j):
            l = 100-i-j-k
            teaspoons = np.array([i,j,k,l])
            # print(teaspoons.sum())
            values = np.dot(matrix_coef, teaspoons)
            if (values <= 0).sum() >= 1:
                pass
            else:
                score = max([score, np.prod(values)])

In [47]:
values[-1]

0

In [44]:
score

13882464

## Part 2

In [48]:
matrix_coef_2 = df_ing.to_numpy()
matrix_coef_2

array([[ 5, -1,  0, -1],
       [-1,  3, -1,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  2],
       [ 5,  1,  6,  8]])

In [53]:
score = 0
for i in range(0,101):
    for j in range(0,101-i):
        for k in range(0,101-i-j):
            l = 100-i-j-k
            teaspoons = np.array([i,j,k,l])
            # print(teaspoons.sum())
            values = np.dot(matrix_coef_2, teaspoons)
            if (values <= 0).sum() >= 1:
                pass
            else:
                if values[-1] == 500:
                    score = max([score, np.prod(values[:-1])])
                else:
                    pass

In [54]:
score

11171160

In [55]:
values

array([ 500, -100,    0,    0,  500])